# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:
  rest-api-2:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL
  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL
  shell-2:
    image: reshu1docker/client-js:latest
    container_name: sawtooth-shell-default-2
    stop_signal: SIGKILL
    environment:
      - REST_API_URL=http://rest-api-2:8008
      - Server_url=http://172.19.111.172:8000
      - cam_url=http://172.19.111.175:8080/video
  validator-2:
    image: adaephonben/validator-rest-2:latest
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - "4004:4004"
      - "5050:5050"
      - "8800:8800"
    command: tail -f /dev/null
    environment:
      MY_IP: ""
      OTHER_IP_1: ""
      OTHER_IP_2: ""
      OTHER_IP_3: ""

  pbft-2:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-2
    command: pbft-engine -vv --connect tcp://validator-2:5050
    stop_signal: SIGKILL
  junction-tp-2:
    image: reshu1docker/junction-tp-js:latest
    container_name: sawtooth-junction-tp-js-default-2
    expose:
      - 4004
    environment: 
      - VALIDATOR_URL=tcp://validator-2:4004
      - INFO=Yes
      - Server_url=http://172.19.111.172:8000
      - cam_url=http://172.19.111.175:8080/video
    stop_signal: SIGKILL
